site_name: Django Cloud Tasks
site_url: https://django-cloud-tasks.flamingo.codes/
nav:
    - 'Getting Started': 'index.md'
    - 'On-Demand Tasks': 'on_demand_tasks.md'
    - 'Scheduled Tasks': 'scheduled_tasks.md'
    - 'Pub/Sub': 'pubsub.md'
    - 'Header Propagation': 'headers.md'
    - 'TaskField (Model Field)': 'task_field.md'
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - content.action.edit
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition # Useful for notes, warnings etc.
  - pymdownx.details # For collapsible admonitions and other features
  - toc:
      permalink: true # Adds anchor links to headings
  - attr_list # Required for custom attributes on icons/emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 