# Generated by Django 4.2.1 on 2023-07-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_cloud_tasks", "0002_alter_routine_status_alter_routine_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="max_retries",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddConstraint(
            model_name="routine",
            constraint=models.CheckConstraint(
                check=models.Q(("max_retries__gte", models.F("attempt_count"))),
                name="max_retries_less_than_attempt_count",
            ),
        ),
    ]
