name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          cache: poetry
      - name: Setup Environment
        run: |
          make setup
      - name: Build & Publish package
        run: |
          make publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
